export const PRODUCT_LIST = [
  "Glutanex Drip",
  "Snow White Drip",
  "ARGINEX-Skinny Drip",
  "Glutanex 1800 Drip",
  "Double Glutanex Drip",
  "Glutanex 1200mg",
  "Gluta-1 1200mg",
  "Glutanex 600mg",
  "Asconex",
  "Asco-1",
  "Liponex-300",
  "Lipo-1",
  "Cartinex",
  "Traminex ",
  "Yuvenis PN",
  "Nextoxin",
  "PLENARIS",
  "PLENARIS PRO",
  "Nexfill",
  "Nexfill PRO",
  "PLENARIS PRO GSH",
  "Glutanex Glow",
  "AHA BHA LHA Ampoule",
  "PLENARIS EXOSOME HGF",
  "Glutanex Tab",
  "Cartinex Tab",
  "Asco-1 Collagen Advanced tabs",
  "Accunex",
  "Glutanex Mask",
  "Glutanex Snow White Cream",
  "Glutanex glutathione Night Serum",
  "Glutanex Sun Stick",
  "Glutanex soap 3 bar set",
  "Glutanex soap 1 bar",
  "Aquanex",
  "Glutanex IN-SHOWER BODY CREAM",
  "Retinol Eye Cream",
  "Glutanex Glow balm",
  "Glutanex Deo Glow Balm",
  "Glutanex UV Glow balm",
  "Glutanex lip glow balm",
  "Glutanex Glow Therapy Ampoule",
  "Glutanex Aqua Booster",
  "Glutanex Spot Removal cream",
  "Glutanex cica cream",
  "GLUTANEX GLOW THERAPY SPECULE SHOT 15000 (Facial)",
  "GLUTANEX GLOW THERAPY SPECULE SHOT 50000 (Body)",
  "Glutanex Glow THERAPY MASK",
  "GLOW THERAPY GEL-TO-FOAM CLEANSER",
  "Glutanex Aloe booster",
  "Nexcain Pro",
  "Nexcain",
  "Bione 600mg",
  "Luthione 1200mg",
  "Cindella Set",
  "DHNP Vitamin C",
  "Multi-vita injection",
  "Beecomhexa",
  "Pyridoxine HCl injection (Vitamin B6)",
  "Hycobal injection",
  "Vita D injection 200,000 IU",
  "Vita D injection 300,000 IU",
  "Fursultiamine HCl Injection",
  "GC Vita 5",
  "Nabota 100IU",
  "Nabota 200IU",
  "Botulax 100IU",
  "Botulax 200IU",
  "Innotox 50IU",
  "Innotox 100IU",
  "Revolax",
  "Neuramis Filler",
  "Atierre",
  "Elasty",
  "Hyaron",
  "Lipotocin",
  "Melsmon",
  "Placein",
  "Laennec",
  "Liporase",
  "Jayblue Injection",
  "Jenasteron",
  "Estradiol Depot",
  "Placentex",
  "Rejuran Healer",
  "Rejuran S",
  "Zinc 10mL",
  "Zinc 20mL",
  "Selinu",
  "Masi Injection",
  "ATP",
  "Ginkgo",
  "Calcium Gluconate",
  "Epinephrine",
  "Calkilate",
  "Nutrihex",
  "Yuvasol",
  "Triamcinolone",
  "Saxenda",
  "Venoferrum",
  "ASCE+ SRLV",
  "ASCE+ HRLV",
  "Collapleo",
  "Lipo Lab Brown",
  "Huons Sodium Bicarbonate Inj.",
  "Tramadol",
  "Butterfly Needles 23G, 24G",
  "Infusion Sets",
  "NSS 50mL",
  "NSS 100mL",
  "NSS 250mL",
  "NSS 500mL"
];
